# https://raw.githubusercontent.com/ory/kratos/v1.2.0/.schemastore/config.schema.json
version: v1.2.0

dsn: memory

serve:
  public:
    base_url: https://ory.#HOST#/
    cors:
      enabled: true
      allowed_origins:
        - https://#HOST#
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Access-Control-Allow-Origin
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://#HOST#
  allowed_return_urls:
    - https://#HOST#
    - https://ory-node.#HOST#
    - https://#HOST#:3000
    - https://#HOST#:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://ory-node.#HOST#/error

    settings:
      ui_url: https://ory-node.#HOST#/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://ory-node.#HOST#/recovery
      use: code

    verification:
      # we disable verification for self-hosting
      enabled: false
      ui_url: https://ory-node.#HOST#/verification
      use: code
      after:
        default_browser_return_url: https://#HOST#/login-result

    logout:
      after:
        default_browser_return_url: https://ory-node.#HOST#/login

    login:
      ui_url: https://ory-node.#HOST#/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://ory-node.#HOST#/registration
      after:
        password:
          default_browser_return_url: https://#HOST#/login-result
          hooks:
            - hook: session
            - hook: show_verification_ui
        default_browser_return_url: https://#HOST#/login-result

session:
  whoami:
    tokenizer:
      templates:
        jwt_template:
          jwks_url: http://host.docker.internal:3000/.well-known/jwks.json
          # claims_mapper_url: base64://... # A JsonNet template for modifying the claims
          ttl: 24h # 24 hours (defaults to 10 minutes)
cookies:
  domain: "#HOST#"
  path: /
  same_site: Lax

log:
  level: warning
  format: json
  redaction_text: ""
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@host.docker.internal:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
